# Generated by Django 4.1.7 on 2023-06-19 07:05

import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_alter_invoiceitem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="invoice_no",
            field=models.CharField(
                default=apps.finance.models.increment_invoice_number, max_length=10
            ),
        ),
    ]
